# Generated by Django 2.1.7 on 2019-03-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brotherhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contact_email', models.CharField(max_length=100)),
                ('foundation_date', models.DateField(blank=True, null=True)),
                ('jump_order', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('jump_order',),
            },
        ),
    ]
